/*
 * 7. Prime numbers can also be generated by an algorithm known as the Sieve of
 * Eratosthenes. The algorithm for this procedure is presented here. Write a
 * program that implements this algorithm. Have the program find all prime
 * numbers up to n = 150. What can you say about this algorithm as compared to
 * the ones used in the text for calculating prime numbers?
 *
 *	Sieve of Eratosthenes Algorithm
 *	To Display All Prime Numbers Between 1 and n
 *	Step 1: Define an array of integers P. Set all elements Pi to 0,
 *			2 <= i <= n.
 *	Step 2: Set i to 2.
 *	Step 3: If i > n, the algorithm terminates.
 *	Step 4: If Pi is 0, then i is prime.
 *	Step 5: For all positive integer values of j, such that i x j ≤ n,
 *			set Pixj to 1.
 *
 * By Faisal Saadatmand
 *
 * NOTE: this is a slight variation on ex7. It wraps the code in a function,
 * generatePrimes, which generates the prime numbers and returns them in an
 * 'array'.
 *
 */

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

/* generatePrimes: returns a pointer to an array (heap allocated) of all prime
 * numbers up to, and including n */
long unsigned *generatePrimes(const size_t n, long unsigned *primes, size_t *primesSize)
{
	unsigned *p;
	size_t i, j, k;

	/* allocate memory for the sieve (array of unsigned int) */
	if (!(p = calloc(sizeof(unsigned), n + 1))) {
		fprintf(stderr, "unable to allocate memory\n");
		exit(EXIT_FAILURE);
	}

	/* allocate memory for the generated prime numbers (array of long
	 * unsigned int) */
	if (!(primes = malloc(sizeof(long unsigned)* (n + 1)))) {
		fprintf(stderr, "unable to allocate memory\n");
		exit(EXIT_FAILURE);
	}

	for (i = 2, k = 0; i < n; ++i) {
		if (p[i] == 0) {
			primes[k++] = i;
			for (j = i * i; j <= n ; j += i)
				p[j] = 1;
		}
	}

	/* clean up */
	free(p);
	p = NULL;

	/* return the size of primes (return parameter) */
	*primesSize = k;

	return primes;
}

int main(void)
{
	long unsigned *primeNumbers, i;
	const size_t n = 1000000;
	size_t setSize = 0;

	primeNumbers = NULL;
	primeNumbers = generatePrimes(n, primeNumbers, &setSize);
	for (i = 0; i < setSize; ++i)
		printf(" %lu", primeNumbers[i]);
	printf("\n");
	free(primeNumbers);
	primeNumbers = NULL;

	return 0;
}
