/* 
 * 3. A triangular number can also be generated by the formula
 *    triangularNumber = n (n + 1) / 2
 * for any integer value of n. For example, the 10th triangular number, 55, can
 * be generated by substituting 10 as the value for n in the preceding formula.
 * Write a program that generates a table of triangular numbers using the
 * preceding formula. Have the program generate every fifth triangular number
 * between 5 and 50 (that is, 5, 10, 15, ...,
 * by Faisal Saadatmand
 */
 
#include <stdio.h>

int main(void)
{
	int n, tri_nu;

	for (n = 5; n <= 50 ; n = n + 5) {
		tri_nu = n * ( n + 1 ) / 2;
		printf("The %2ith triangular number is %i\n", n, tri_nu);
	}
	return 0;
}
	
